=== ESMCI/sourceTreeFetch/source_info.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://github.com"
           xmlns="https://github.com"
           elementFormDefault="qualified">

  <xs:complexType name="sourceType">
    <xs:element name="source" type="xs:string" maxOccurs="unbounded"
                minOccurs="1`">
      <xs:complexType>
        <xs:element name="repo" type="xs:string" maxOccurs="unbounded"
                    minOccurs="1`">
          <xs:complexType>
            <xs:attribute name="protocol" type="xs:string" use="required"/>
            <xs:attribute name="root" type="xs:string" use="required"/>
            <xs:attribute name="ref" type="xs:string" use="optional"/>
            <xs:attribute name="sub_treepath" type="xs:string" use="optional"/>
          </xs:complexType>
        </xs:element>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="tree_path" type="xs:string" use="required"/>
        <xs:attribute name="externals" type="xs:string"
                      use="optional" default="false"/>
      </xs:complexType>
    </xs:element>
    <xs:attribute name="location" type="xs:string"
                  use="optional" default="externals"/>
  </xs:complexType>

  <xs:complexType name="stagingType">
    <xs:element name="staging" dir="xs:string">
      <xs:element name="source" type="sourceType" />
    </xs:element>
  </xs:complexType>

  <xs:element name="sourceTree">
    <xs:complexType>
      <xs:element name="source" type="sourceType" use="optional" />
      <xs:element name="staging" type="stagingType" use="optional" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== ESMCI/sourceTreeFetch/CESM.xml
<?xml version='1.0' encoding='utf-8'?>

<sourceTree xmlns="http://spot.colorado.edu"
            xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
            xs:schemaLocation="http://spot.colorado.edu/~goldy/CESM/source_info.xsd">
  <source name="CESM"
          tree_path="cesm">
    <repo protocol="git"
          root="https://github.com/ESMCI/CoupledInfrastructure.git"
          ref="master" />
  </source>
  <source name="CAM"
          tree_path="cesm/models/atm/cam">
    <repo protocol="svn" 
          root="https://svn-ccsm-models.cgd.ucar.edu/cam1/branches/newtesting/models/atm/cam" />
  </source>
  <source name="CISM"
          tree_path="cesm/models/glc/cism">
    <repo protocol="svn" 
          root="https://svn-ccsm-models.cgd.ucar.edu/glc/branches/newtesting" />
  </source>
  <source name="CICE"
          tree_path="cesm/models/ice/cice">
    <repo protocol="svn" 
          root="https://svn-ccsm-models.cgd.ucar.edu/cice/branches/newtesting" />
  </source>
  <source name="CLM"
          tree_path="cesm/models/lnd/clm">
    <repo protocol="svn" 
          root="https://svn-ccsm-models.cgd.ucar.edu/clm2/branches/newtesting/models/lnd/clm" />
  </source>
  <source name="POP2"
          tree_path="cesm/models/ocn/pop2">
    <repo protocol="svn" 
          root="https://svn-ccsm-models.cgd.ucar.edu/pop2/branches/newtesting" />
  </source>
  <source name="RTM"
          tree_path="cesm/models/rof/rtm">
    <repo protocol="svn" 
          root="https://svn-ccsm-models.cgd.ucar.edu/rivrtm/branches/newtesting" />
  </source>
  <source name="MCT"
          tree_path="cesm/models/utils/mct">
    <repo protocol="git" 
          root="git@github.com:MCSclimate/MCT.git"
          ref="tags/NagFix_MCT_2.8.3" />
  </source>
  <source name="PIO"
          tree_path="cesm/models/utils/pio">
    <repo protocol="svn" 
          root="https://parallelio.googlecode.com/svn/trunk_tags/pio1_9_10/pio" />
  </source>
  <source name="WW3"
          tree_path="cesm/models/wav/ww3">
    <repo protocol="svn" 
          root="https://svn-ccsm-models.cgd.ucar.edu/ww3/branches/newtesting" />
  </source>
</sourceTree>
